### ISSUE TITLE
Użytkownicy - nowa strona serwisu

### ISSUE THREAD

**Issue by furious-programming** [pradoslaw/coyote#111]
Przydatna rzecz - strona z listą wszystkich zarejestrowanych użytkowników. Przydatna nie tylko dla ciekawskich, ale również dla moderatorów.

Oprócz widoku listy użytkowników (np. w postaci kafelek), możliwe także sortowanie według ID, alfabetycznie, a także według punktów reputacji i liczby postów. Dodatkowo pole edycyjne do wyszukiwania użytkownika(ów) na podstawie zadanego podciągu/regexa oraz podanej lokalizacji.

Dostęp do tej strony możliwy z nowej pozycji menu głównego - **Użytkownicy**. Wygląd strony (kafli) można podpierdzielić ze **Stacka**, w razie braku pomysłów.

**Comment by adamwojs** [comment]
Temat jest aktualny ? Jeśli tak to chętnie się go podejmę ;-)

**Comment by adam-boduch** [comment]
Tak, aktualny :) Fajnie, że chcesz się go podjąć. Ustalmy może założenia. 

1) Jeżeli chodzi o prezentację listy użytkowników to proponowałbym jednak listę w postaci tabelarycznej, tak jak w panelu administracyjnym (zakładka *Użytkownicy*) gdzie lista prezentowana jest jako tabela (masz dodatkowo możliwość sortowania klikając w nazwę kolumny)

2) Przykład, jak można "podejść" do tego problemu:

```php
public function index()
{
    $grid = $this->gridBuilder()->createGrid(UsersGrid::class);
    $grid->setSource(new EloquentSource($this->user->newQuery()));

    return $this->view('adm.user.home', ['grid' => $grid]);
}
```

Jak widzisz, tutaj masz gotową klasę `UsersGrid`, która wygeneruje Ci całą tabelkę wraz z sortowaniem. Naturalnie klasa `UsersGrid` generuje listę użytkowników z przeznaczeniem dla moderatorów (bo zawiera IP, adres e-mail itp :))

3) Być może link do pełnej listy można by było umieścić tutaj?

![image](https://cloud.githubusercontent.com/assets/10835050/22240479/b30055fc-e21b-11e6-9410-6f80c120b72b.png)

4) Jeżeli chodzi o link do pełnej listy użytkowników w menu głównym: trochę ciasno się tam robi. Kolejna zakładka (link) IMHO sprawi problem na mniejszych szerokościach ekranu. Po prostu nie zmieści się. Alternatywy:

- dodanie zakładki "Inne", a "pod nią" dopiero link do *Użytkownicy*, czy *Pastebin* oraz *Czat*?
- zmiana graficzna tych zakładek?

**Comment by adamwojs** [comment]
To brzmi jak plan ;-)

AD 1) Może być lista w postaci tabelarycznej, oczywiście z zachowaniem spójność graficznej z listą ofert pracy czy forum
AD 3) To dobry pomysł, warto żeby link prowadził od razu do listy posortowanej wg. reputacji 
AD 4 i 5)  Zobaczymy "w praniu" jak wyjdzie. Jak będę miał coś więcej to otworze pull requesta do dyskusji / podglądu zmian.

**Comment by furious-programming** [comment]
Drugi paragraf z mojego pierwszego wpisu w tym zgłoszeniu zawiera to czego mi brakuje.

> ##### Adam:
> Jeżeli chodzi o link do pełnej listy użytkowników w menu głównym: trochę ciasno się tam robi. Kolejna zakładka (link) IMHO sprawi problem na mniejszych szerokościach ekranu. Po prostu nie zmieści się.

Przecież na mniejszych rozdziałkach i tak te pozycje są ukrywane do hamburgera, więc nie widzę tutaj żadnego problemu z nową pozycją. Według mnie link do listy użytkowników musi się znajdować w menu głównym serwisu, bo jest to całkiem osobny dział, całkiem osobna strona z unikalną funkcjonalnością, więc musi być odpowiednio wyeksponowana.

> Jakie kolumny na liście użytkowników?

To co w **vcard** spokojnie wystarczy. Wygląd i układ w okienku **vcard** jest na tyle przyjemny, że można by zastosować dokładnie taki sam układ tych elementów w gridzie z listą użytkowników, czyli:

1. nazwa użytkownika,
2. miniaturka,
3. dostępność,
4. funkcja w serwisie,
5. ostatnia aktywność,
6. data rejestracji,
7. pasek reputacji,
8. guziki do:
8.1. szukania postów,
8.2. wysłania wiadomości prywatnej,
8.3. guziki moderatorskie, widoczne tylko dla modów rzecz jasna.

Ciemnoszara ramka raczej nie będzie wizualnie pasować, ale są inne ramki dobrze by komponujące się z tymi kafelkami, np. ramka wpisu na blogu.

**Comment by adam-boduch** [comment]
@furious-programming wezmy np. taka szerokosc:

![image](https://cloud.githubusercontent.com/assets/10835050/22302584/ac3db2f4-e32f-11e6-845c-2312dafd0225.png)

Kolejna pozycja juz nie wejdzie. Czyli trzeba bylo zawijac menu (do postaci "hamburgowej") juz przy szerokosci 1200px. Trzeba przebudowac menu aby wszystko tam "scisnac". 

Zgadzam sie, ze link do listy uzytkownikow moze byc widoczny w menu, tylko trzeba sie zastanowic w jakiej formie :)

**Comment by furious-programming** [comment]
Wejdzie, bo coś się ukryje - albo schowa się wyszukiwarka, albo logo zmieni się na samą ikonkę, bez `4programmers.net`. Tak jest już teraz - u siebie nie widzę ani wyszukiwarki, ani długiego loga:

![menu](https://cloud.githubusercontent.com/assets/8170730/22309529/e7b021fc-e34b-11e6-8891-b1333dedf24f.png)

Jak widzisz, miejsce samo się znajdzie `:)`

**Comment by adam-boduch** [comment]
Nom, na Twojej szerokości się nie mieści pole wyszukiwania :)

**Comment by adamwojs** [comment]
Zrobiłem małą makietę rozwiązania tabelarycznego: https://dl.dropboxusercontent.com/u/435780/Zrzut%20ekranu%20z%202017-01-26%2000-52-23.png  . 

Pod jakim URI widzicie tą listę użytkowników ? Ja proponuje żeby był to `/Profile`

**Comment by adam-boduch** [comment]
Niestety `/Profile` jest zajęte: pod tym URL wyswietla sie profil danego uzytkownika.
`/User` też zajęte. Moze `/Users`? (liczba mnoga)?

**Comment by furious-programming** [comment]
`/Users` - skoro znajduje się na tej stronie lista wielu użytkowników.

@adamwojs: ładne, ale kafelki były by ładniejsze `:P`

**Comment by adamwojs** [comment]
To zróbmy przełącznik widoku z listowego na kafelkowy ;-)

**Comment by furious-programming** [comment]
Może być i tak - byle ustawienie było zapamiętywane trwale, nie w ciasteczkach `:)`

Przy okazji, @adamwojs - w Twoim szkicu brakuje jeszcze sortowania po **ID**.

**Comment by adamwojs** [comment]
Chwile musiałem odpuścić, ale wracam do akcji.  Podsumowując prace na dzień dzisiejszy:

- Gotowa jest wersja tabelaryczna.   
- Dodałem licznik wpisów na mikroblogu przy w tabeli users (analogicznie do postów oraz reputacji)
- W menu głównym pogrupowałem pozycje "Pastebin", "Czat" oraz "Użytkownicy" w "Inne". Pod reputacją na SG dodałem link "Pełna lista użytkowników"

Zrzut ekranu aktualnej wersji: https://dl.dropboxusercontent.com/u/435780/Zrzut%20ekranu%20z%202017-02-11%2019-07-48.png

Mam dwa pytania do założeń:

- Wyszukiwanie użytkowników po nazwie robimy w oparciu od ES ? 
- Co proponujecie wyświetlać w lewym panelu listy użytkowników ?

**Comment by adam-boduch** [comment]
IMHO, wyszukiwarka nie musi byc na Elasticsearch. Szkoda zachodu: postgres spokojnie poradzi sobie z filtrowaniem/wyszukiwaniem tak malej tabeli :)

**Comment by adam-boduch** [comment]
Ściągam etykietę "in progress" bo chyba zadanie po 2 latach zostało porzucone ;)

**Comment by silvuss** [comment]
@adamwojs Coś w temacie?
