### ISSUE TITLE
Tryb nocny / ciemne tło

### ISSUE THREAD

**Issue by KrzaQ** [pradoslaw/coyote#129]
Fajnie by było gdyby był odgórny support dla ciemnego tła serwisu.

**Comment by adam-boduch** [comment]
Powiem szczerze: czarno to widze. Musialby ktos sie zajac tym tematem, a nie jest to tylko "jednorazowa" akcja. Potem dochodzi utrzymanie takiej "skorki" wraz z rozwojem nowej funkcjonalnosci.

**Comment by KrzaQ** [comment]
Właśnie dlatego proszę o odgórny support ;)

**Comment by adam-boduch** [comment]
Projekt jest Open Source więc może ktoś się tym tematem przejmie :P

**Comment by DorianMazur** [comment]
I am working on this :D

**Comment by adam-boduch** [comment]
Wprowadzony ciemny nagłówek (o takim samym kolorze jak stopka). Póki co można włączyć opcjonalnie (nie jest domyślnie włączony dla wszystkich użytkowników).
