### ISSUE TITLE
Automatycznie plusowanie akceptowanego posta

### ISSUE THREAD

**Issue by furious-programming** [pradoslaw/coyote#157]
Wcześniej było tak, że użytkownik będący właścicielem wątku lub moderator klikając na fajeczkę przy poście powodował zaznaczenie fajeczki i od razu automatyczne zaplusowanie akceptowanego posta. Teraz brakuje automatycznego plusowania.

**Comment by adam-boduch** [comment]
znasz 4p lepiej niz ja ;p szczerze mowiac, nie pamietam tej funkcjonalnosci :D

**Comment by KrzaQ** [comment]
Potwierdzam, że tak było :)

**Comment by Marooned-MB** [comment]
Adam, ale sam ją zasugerowałeś ;)
https://4programmers.net/Forum/Coyote/216008-reputacja_?p=981978#id981978
> A co myslicie o pomysle, aby dawac +1 pkt autorowi watku, ktora zaakceptuje odpowiedz?

**Comment by Marooned-MB** [comment]
Rzeczywiście, kto inny jest adresatem +1 w obu sugestiach.

**Comment by adam-boduch** [comment]
@Marooned-MB heh, skleroza ;) 
@KrzaQ dobry pomysł :)

**Comment by silvuss** [comment]
Ciekawe rozwiązanie, by dawać punkty też autorowi wątku. Być może potrzeba by było ankiety.

Widzę jedną zaletę: może zachęcić do akceptacji odpowiedzi. Niestety, jest to także wada; może zachęcić do akceptacji nawet wtedy, gdy dana odpowiedź nieszczególnie odpowiada na pytanie wątku – na przykład gdy użytkownikowi nie chce się czekać na kolejne odpowiedzi (i choć dana odpwiedź nie jest dobra, to jest najlepsza z możliwych), albo uznał, że już raczej nikt w wątku nie napisze.
