### ISSUE TITLE
Kolorowanie ofert pracy zawierających ulubione tagi

### ISSUE THREAD

**Issue by furious-programming** [pradoslaw/coyote#231]
Wątki zawierająca ulubione tagi, na liście wątków w danej kategorii kolorowane są na pomarańczowo - dzięki temu przyciągają wzrok. Myślę, że fajnie by było, gdyby w ten sam sposób były kolorowane oferty pracy w kategorii `Praca` - zawierające ulubiony tag tak samo na pomarańczowo, a pozostałe na biało.

**Comment by adam-boduch** [comment]
Niezły pomysł :)

**Comment by adam-boduch** [comment]
Proponuje zmiane graficzna samego tagu, zamiast podswietlanie wiersza. Byc moze opcje podswietlania wiersza damy jaka dodatkowa opcje platna dla pracodwacy, przy wystawianiu ofert.

**Comment by furious-programming** [comment]
Jeśli podświetlanie będzie opcją dodatkową (płatną) to użytkowników może to mylić. Póki co użytkownik przyzwyczajony jest do tego, że podświetlony wątek pasuje do jego upodobań (np. umiejętności), dzięki temu wszystkie podświetlone pozycje na pewno go zainteresują. Jeśli oferty pracy będą podświetlane według innych kryteriów to na pewno będzie to mylące.

Jeśli chodzi o płatne dodatki do ofert, to może by pójść w nieco innym kierunku? Np. za dodatkową opłatą oferta będzie **promowana**, tak jak w **allegro**, czyli np. podbijana na górę listy?

Dzięki temu podświetlanie na pomarańczowo było by zgodne z wyglądem zawartości kategorii forum, nie rezygnując z zarobku na ofertach. Trzeba by tylko zastanowić się nad tym, w jaki sposób eksponować te specjalne oferty (z dopłatą), tak aby nie odbierać zainteresowania zwykłymi ofertami.

**Comment by adam-boduch** [comment]
Tak, w przypadku opcji promowania, ogloszenie musi byc na samej gorze listy :) to takie "must have" :P
