### ISSUE TITLE
Nieprawidłowa etykieta do wysyłania odpowiedzi w wątku

### ISSUE THREAD

**Issue by furious-programming** [pradoslaw/coyote#271]
Na dole każdego otwartego wątku znajduje się pole do pisania odpowiedzi, a pod nim przycisk `Zapisz` do jej wysłania. Dlaczego ten przycisk jest zatytułowany `Zapisz`, a nie np. `Odpowiedz` czy `Wyślij`?

Ta funkcja raczej nie służy do zapisywania (co sugeruje zapis modyfikacji), więc przycisk ten nie powinien być tak zatytułowany.

Sugeruję zmianę jego treści na `Wyślij odpowiedź` lub `Opublikuj post`.

**Comment by adam-boduch** [comment]
Ten sam formularz służy edycji, odpowiedzi itp. Myślę, że każdy rozumie o co chodzi :P Jednak gdyby ktoś był chętny do tej drobnej poprawki to zapraszam :)

**Comment by furious-programming** [comment]
Treść tego przycisku mnie nie przeszkadza, bo bardzo rzadko z niego korzystam (wolę `Ctrl+Enter`). Zgłosiłem to w ramach estetycznego ulepszenia serwisu.

Jeśli uważasz, że to nie ma większego znaczenia to może tak zostać `:)`

**Comment by adam-boduch** [comment]
Na github np. etykieta przycisku zmienia sie w zaleznosci czy dodajemy komentarz czy go edytujemy. Owszem - zadanie ma niski priorytet, ale poki co zostawiam, bo moze ktos bedzie chcial poprawic :)

**Comment by danon** [comment]
Poprawione z c065eb04
