### ISSUE TITLE
Funkcjonalność dla moderatorów: zmiana posta w komentarz do posta

### ISSUE THREAD

**Issue by furious-programming** [pradoslaw/coyote#298]
Analogicznie do zgłoszenia #260

Możliwość zamiany posta na komentarz (jeśli zawiera off-topic). Post powinien być usunięty (standardowo, aby była możliwość jego przywrócenia), a komentarz dodany do poprzedniego posta, według daty publikacji.

**Comment by Marooned-MB** [comment]
Nie mam pewności, czy to dobry pomysł. Bywają takie sytuacje:
* post 1
* post 2
* post dot. post 1 (powinien być komentarzem)
wtedy automatyczne przeniesienie komentarza do post 2 byłoby błędem

Pomijam, że często te posty zamiast komentarzy są autorstwa niezalogowanych, a tych nie można przerobić na komentarze.

**Comment by furious-programming** [comment]
W takich przypadkach pozostaje standardowa akcja, czyli usunięcie postu (**Off-Topic** jako powód).

Czas pokaże, czy taka funkcjonalność będzie przydatna. Póki co kilka razy spotkałem się z sytuacją, kiedy to wspomniana opcja przydała by się.
