### ISSUE TITLE
Kłopotliwe usuwanie konwersacji prywatnych

### ISSUE THREAD

**Issue by furious-programming** [pradoslaw/coyote#365]
W chwili obecnej, możliwe jest usuwanie konwersacji z użytkownikami jedynie pojedynczo, co przy większej ich liczbie jest niewygodne i czasochłonne.

Sugeruję zamienić przyciski krzyżyków na pola typu checkbox oraz dodać przycisk (lub checkbox) do zaznaczania/odznaczania wszystkich rozmów i drugi do usuwania tych zaznaczonych. Dzięki temu będzie można szybko i wygodnie (dwoma kliknięciami) usunąć wszystkie rozmowy. Natomiast usuwanie tylko wybranych rozmów będzie znacznie szybsze i wygodniejsze od obecnego.

**Comment by adam-boduch** [comment]
O ile mnie pamiec nie myli mozna usunac cala konwersacje z danym uzytkownikiem. Po prostu.

**Comment by furious-programming** [comment]
Chyba mnie nie zrozumiałeś – chodzi o usunięcie całych konwersacji z wieloma użytkownikami oraz o usunięcie wszystkiego co znajduje się w skrzynce.

Teraz, aby doszczętnie wyczyścić skrzynkę wiadomości, trzeba każdą rozmowę kasować z osobna. Jeśli mam na skrzynce rozmowy z dziesięcioma użytkownikami (ilość peemek w każdej rozmowie nie jest istotna) to muszę dziesięć razy kasować po jednej pełnej rozmowie – nie mogę wywalić wszystkiego od razu.
