### ISSUE TITLE
Tworzenie nowego wątku - ankieta bez tytułu

### ISSUE THREAD

**Issue by aurell** [pradoslaw/coyote#390]
Gdy stworzymy wątek z ankietą, ale nie wpiszemy nic w pole tytułu ankiety, to ankieta się nie pojawia, choć post zostaje opublikowany. Po wejściu w edycję postu nie widać ankiety.

**Comment by adam-boduch** [comment]
Zgadza sie. Jak nie podasz tytulu, to ankieta nie zostaje w ogole dodana do bazy. To jest celowe dzialanie, a nie bug. Rozumiem, ze chodzi Ci o sytuacje w ktorej chcesz dokonczyc ankiete w pozniejszym czasie, dodajac tylko tytul?

**Comment by aurell** [comment]
Jako użytkownika, zdziwiło mnie, że napisałam trochę punktów, a one sobie po prostu zniknęły. Skoro nie było gwiazdki przy polu tytułu, to myślałam, że nie jest on wymagany. Nie widzę z resztą sensu tego pola, bo IMHO tytuł wątku jest wystarczający.

**Comment by adam-boduch** [comment]
Hmm, ciekawy pomysł z tym brakiem tytułu dla ankiety. Chyba masz racje :-)

**Comment by Marooned-MB** [comment]
Na pewno uznałbym za bug to, że coś znika bez powiadomienia usera. Bez względu czy pole z tytułem zostanie czy nie.
