### ISSUE TITLE
Nieprawidłowy link do widoku kategorii forum psuje listę aktywnych użytkowników

### ISSUE THREAD

**Issue by furious-programming** [pradoslaw/coyote#400]
Zakładka `Kategorie` np. w [widoku wszystkich wątków](https://4programmers.net/Forum/All) kieruje pod adres:

https://4programmers.net/Forum/Categories

podczas gdy przycisk `Forum` w głównym menu serwisu kieruje do:

https://4programmers.net/Forum.

Pod tym pierwszym z reguły nie ma nikogo innego, więc lista aktywnych użytkowników zawsze zawiera jedną pozycję (czyli własny nick).

Trzeba poprawić adres w tej zakładce, aby był taki sam jak ten pod przyciskiem głównego menu, albo w obu przypadkach wyświetlać listę użytkowników będących na stronie z kategoriami forum.

**Comment by silvuss** [comment]
Moim zdaniem, skoro widok jest taki sam, nie ma sensu kierowanie do dwóch różnych adresów.
