### ISSUE TITLE
Wizualna wskazówka, że OP może w każdej chwili usunąć wątek

### ISSUE THREAD

**Issue by KrzaQ** [pradoslaw/coyote#485]
W nawiązaniu do: #444 

Produkowanie się nad odpowiedzią, żeby OP ją zaraz usunął bo np. uznał swój błąd za głupi jest bardzo deprymujące. Chciałbym więc jakieś oznaczenie, że "w tym wątku można bezpiecznie odpowiadać".

**Comment by adam-boduch** [comment]
Dobry pomysł. Masz jakiś pomysł jak można by wizualnie rozwiązać?

**Comment by silvuss** [comment]
@KrzaQ: ale kiedy w danym wątku można by było "bezpiecznie odpowiadać", a kiedy nie?

**Comment by KrzaQ** [comment]
Wtedy kiedy OP nie może usunąć wątku.

adam-boduch: przepraszam, nie zauważyłem notyfikacji. Może jakaś kłódeczka, czy coś przy pierwszym poście? Nie mam pomysłu, ale już kilka razy naciąłem się i chciałbym takiej funkcjonalności.

**Comment by silvuss** [comment]
@KrzaQ Ale właśnie o to mi idzie. W jakich sytuacjach OP ma nie móc usunąć wątku?

**Comment by KrzaQ** [comment]
@silvuss Idealnie chciałbym, aby tak było gdy w wątku są odpowiedzi, ale nie da się ( #444 ). Jak zauważyłem w pierwszym poście, czasem przygotowanie odpowiedzi zajmuje kilkanaście minut, za które nikt mi nie płaci. Jeśli autor może odebrać mi jeszcze "bragging rights" to wolę poświęcić czas na bardziej produktywne rzeczy.

A w tym przypadku chciałbym wiedzieć kiedy spełnione są kryteria uniemożliwienia usunięcia tematu przez OP-a.

**Comment by silvuss** [comment]
OK, rozumiem – czyli idealnie żaden użytkownik, nawet najbardziej doświadczony czy najdłużej tu będący, ma nie móc usuwać żadnego z wątków, które założył. Ale ja nie widzę w #444 podanych żadnych przeciwskazań. Kwestia podejścia (Adama).

Jak rozumiem, w sytuacji gdy dany użytkownik uzna, że wątek rzeczywiście powinien zostać skasowany, powinen napisać do moderatora?

**Comment by silvuss** [comment]
OK, rozumiem – czyli idealnie żaden użytkownik, nawet najbardziej doświadczony czy najdłużej tu będący, ma nie móc usuwać żadnego z wątków, które założył. Ale ja nie widzę w #444 podanych żadnych przeciwskazań. Kwestia podejścia (@adam-boduch ).

Jak rozumiem, w sytuacji gdy dany użytkownik uzna, że wątek rzeczywiście powinien zostać skasowany, powinen napisać do moderatora?

**Comment by KrzaQ** [comment]
Ale chwila, nie o tym tu teraz rozmowa. W #444 ustaliliśmy, że "it's not a bug, it's a feature". W #485 jedyne o co proszę, to o informowanie kiedy to feature jest aktywne. Czyli kiedy użytkownik może skasować swój post z moj odpowiedzią.

**Comment by silvuss** [comment]
Masz rację, niemal zapomniałem, czego dotyczy ta issue. ;) Ale piszę właśnie "idealnie". Czyli że – Twoje pytanie w tej issue może nie być aktualne, jeśli Adam uzna, że rzeczywiście można to zmienić. Ale Twoja wola oczywiście.

…Ach, już rozumiem. Chodzi Ci o ten krótki czas od rejestracji, w którym użytkownik nie może usunąć wątku.

**Comment by silvuss** [comment]
Masz rację, niemal zapomniałem, czego dotyczy ta issue. ;) Ale piszę właśnie "idealnie". Czyli że – Twoje pytanie w tej issue może nie być aktualne, jeśli Adam uzna, że rzeczywiście można to zmienić. Ale Twoja wola oczywiście.

…Ach, już rozumiem. Chodzi Ci o ten (krótki?) czas od rejestracji, w którym użytkownik nie może usunąć wątku.

**Comment by KrzaQ** [comment]
Idealnie to bym chciał, żeby wątek, w którym są odpowiedzi, mógł usunąć tylko ktoś z uprawnieniami co najmniej moderatora. Ale skoro to była przemyślana decyzja, to zapewne dla forum jako biznesu bilans zysków i strat jest dodatni :)

**Comment by silvuss** [comment]
@KrzaQ Tak sobie myślę, że żeby Twoja propozycja miała sens, to i tak trzeba zmienić reguły pozwalające na usuwanie własnych wątków.

Obecnie zawsze przecież może się zdarzyć, że podczas pisania odpowiedzi użytkownik uzyska wystarczającą liczbę punktów (punkty, zdaje się, liczone są u nas z pewnym opóźnieniem) – i niezależnie, czy będzie tego świadomy, czy nie, to może spróbować usunąć wątek.

Chyba że liczysz, że to będzie na tyle rzadka sytuacja, że nie ma o co kruszyć kopii (osobiście wolałbym trzymać się reguł, które zawsze działają).

**Comment by KrzaQ** [comment]
Wystarczy, że informacja będzie prawdziwa na moment sprawdzenia. Licznika postów czy statusu zamknięcia tematu też przecież nie aktualizujemy bez odświeżenia strony.

**Comment by silvuss** [comment]
Dla Ciebie będzie prawdziwa, ale dla serwera nie. Wszelkie informacje graficzne służą naszej wygodzie, a nie mówią nic / mówią niewiele o bieżącym stanie serwera. Jak naciśniesz `Zapisz`, to w przypadku gdyby wątek został w międzyczasie usunięty, serwer i tak Twój post odrzuci.

**Comment by KrzaQ** [comment]
Nie rozumiem Twojego problemu. Jak OP nie może usunąć wątku to go nie usunie. I o tym dokładnie chcę zostać poinformowany.

**Comment by silvuss** [comment]
Ale ja mówię o sytuacji, kiedy Ty myślisz, że nie może usunąć (bo takie informacje przesłał Tobie serwer), a on jednak może (bo stan bazy zmienił się w czasie pisania przez Ciebie postu).

**Comment by silvuss** [comment]
PS. Można by ewentualnie zrobić tak, by stan "może/nie może usunąć" był podawany zapytaniem AJAX – wtedy, tak sądzę, byłaby naprawdę minimalna szansa, żebyś miał nieaktualną informację (chyba że sam jej nie sprawdzisz przed naciśnięciem `Zapisz`).

**Comment by KrzaQ** [comment]
To sytuacja analogiczna do zamknięcia wątku/przeniesienia do Kosza. Też nie ma o tym informacji na żywo i nie widzę potrzeby aby była. I tak głównymi winowajcami w takich przypadkach są prawie zawsze userzy z 1 postem (albo postami tylko w jednym temacie) i 0 reputacji. Na razie ręcznie patrzę na godzinę utworzenia tematu i odczekuję 60 minut przed odpowiedzią, ale to jest irytujące.

**Comment by silvuss** [comment]
W porządku. Niemniej moim zdaniem pokazywanie informacji na bieżąco, a nie do odświeżenia strony, byłoby w tym przypadku najbardziej sensowne (zarówno o usunięciu przez OP, jak i moderatora).

**Comment by adam-boduch** [comment]
Ostatnio zaszly zmiany: uzytkownik nie moze skasowac swojego postu jezeli ktos pozniej napisal juz odpowiedz. No chyba, ze jest to uzytkownik ze stosowna liczba punktow reputacji (300 o ile pamietam), ale tacy raczej nie kasuja od tak swoich postow. Zastanawiam sie wobec tego czy to zadanie ma nadal reacje bytu? hmm?
