### ISSUE TITLE
API do Coyote 2.0

### ISSUE THREAD

**Issue by adam-boduch** [pradoslaw/coyote#52]
Zakres funkcjonalnosci: do dyskusji.

_Zalozenia_:
- Sciezki takie same jak do glownej czesci serwisu, z ta roznica ze w subdomenie api.4programmers.net
- Wersjonowanie API, czyli api.4programmers.net/1.0/Forum/Newbie..
- W pierwszej kolejnosci mozliwosc przegladania, a w dalszej - logowania oraz dodawania materialow
- Format danych: JSON API (http://jsonapi.org/)
- Biblioteka: http://fractal.thephpleague.com/

**Comment by bkielbasa** [comment]
Ode mnie mogę dodać potrzebę api do mikroblogów

**Comment by Koziolek** [comment]
Dostęp do serwisu za pomocą API, czyli mogę się zalogować, przejrzeć powiadomienia, wiadomości, mikrobloga.

**Comment by msm-code** [comment]
I będzie można napisać konsolowy klient 4p!

A tak poważnie - API do najnowszych tematów,, najlepiej z tagiem (czegoś takiego używają na ircu do bota).

**Comment by bkielbasa** [comment]
jakieś plany w tym temacie?
Można by rozważyć również użycie np graphql'a

**Comment by adam-boduch** [comment]
Tak. Jest już pierwszy endpoint: https://4programmers.net/Forum/1584454

Zobacz też: https://4programmers.net/Forum/Coyote/325514-api_authentication_w_jakiej_formie
