### ISSUE TITLE
Wielokrotna notyfikacja o wspomnieniu w poście po jego edycji

### ISSUE THREAD

**Issue by KrzaQ** [pradoslaw/coyote#541]
Botek wspomniał o mnie w poście. Potem dostawałem notyfikację o każdej edycji tego posta:

![](https://i.imgur.com/JuW2vAU.png)

Bardzo mi się podoba, że są notyfikacje po wspomnieniu w edycji, ale dodałbym chociaż jakiegoś diffa vs poprzednią wersję, żeby tylko nowe mentiony notyfikować ;​)

![](https://i.imgur.com/eiCnw09.png)

**Comment by adam-boduch** [comment]
Tak, niestety jest to póki co taki "minus" tego rozwiązania o którym pisałem tutaj: https://4programmers.net/Forum/Coyote/339018-powiadomienia_o_wystepieniu_loginu_w_tresci_rowniez_po_edycji_postu

**Comment by Danon** [comment]
Możnaby zrobić małego hacka, tzn sparsować wystąpienia nicku w przed i po. I jeśli `diff` == 0, to nie wysyłać powiadomienia. Wysyłać tylko dla nicków które są w "po", a nie ma ich w "przed".

Ma to oczywiście tą wadę, że jeśli ktoś edytuje post i usunie nick, a potem edytuje znowu i doda, to poleci notyfikacja. Ale przynajmniej nie poleci dla poprawek literówek.
