### ISSUE TITLE
Zablokowani uzytkownicy pojawiaja sie w komentarzach do watku pomimo blokady

### ISSUE THREAD

**Issue by daniel1302** [pradoslaw/coyote#722]
Jak w tytule. Zablokowalem uzytkownika X, Nie widze jego watkow, mam za to taki komunikat jak nizej: 
<img width="521" alt="image" src="https://user-images.githubusercontent.com/1239637/234531463-58f25001-d8b9-485c-a391-558d5c8a81bb.png">

Natomiast w komentarzach pod postem innego uzytkownika widze jego wypowiedzi. 

Uzytkownik jest w liscie zablokowanych

**Comment by wojtekxtx** [comment]
@daniel1302 błąd relacji bazy danych? @pradoslaw @adam-boduch ?

**Comment by wojtekLs** [comment]
@danon css/js?

**Comment by danon** [comment]
@wojtekLs Nie ma żadnego technicznego powodu czemu to nie zostało dodane - to jest po prostu funkcjonalność, która nie została jeszcze zaimplementowana.
