### ISSUE TITLE
Ogłoszenia o pracę - ucięta lista technologii.

### ISSUE THREAD

**Issue by Krzysiekop** [pradoslaw/coyote#723]
Zauważyłem uciętą listę wyboru technologii pod wyszukiwarką na głównej stronie ofert pracy: [Praca](https://4programmers.net/Praca)

**Stan obecny**

![defekt](https://github.com/pradoslaw/coyote/assets/38114136/623e07a3-03de-4390-9553-a0a03a68c636)

W źródle strony widać więcej tagów technologii, jednak nie są widoczne.

**Oczekiwany rezultat**

Sugeruję możliwość przesuwania listy za pomocą myszki lub suwaka.
Sugeruję również posegregować technologie pod względem popularności. Aktualnie nie widać np. Android, a są dużo mniej popularne języki.

**Środowisko**

Błąd występuje na wszystkich popularnych przeglądarkach i rozdzielczościach

Mam nadzieję, że pomogłem :)

**Comment by Danon** [comment]
Lepiej byłoby dodać wrap.
