### ISSUE TITLE
"Krzaczki" we wpisach mikrobloga

### ISSUE THREAD

**Issue by olekstomek** [pradoslaw/coyote#745]
Losowo i kilkukrotnie mając otwartą konsolę przeglądarki i klikając po 4programmers natrafiłem na taki problem ze znakami i ułożeniem elementów:
![image](https://github.com/pradoslaw/coyote/assets/26818304/f2d720ac-1205-4196-b649-f3e38c014875)
Na razie nie znalazłem zależności. Może ktoś napotkał taki problem również? 

Microsoft Edge Version 119.0.2151.44 (Official build) (64-bit)

**Comment by danon** [comment]
To przez przekroczenie limitu requestów do fontawesome.
