### ISSUE TITLE
Nakładające się na siebie napisy

### ISSUE THREAD

**Issue by Barto-Paja** [pradoslaw/coyote#754]
Rozmiar okna 1080x1920.
Jeżeli jest n wyświetleń, to wszystko jest w porządku, natomiast jak już mamy przy temacie n wyświetlenia, to wtedy napisy nakładają się na siebie z kategorią forum.
![image](https://github.com/pradoslaw/coyote/assets/24964850/a2609abe-81b1-4d62-95c0-1c0540051c9f)

**Comment by Barto-Paja** [comment]
- 1200x1920 - w porządku
- 1080x1920 na monitorze 1200x1920 też wygląda w porządku
- 1080x1920 fizycznie mogę potwierdzić dopiero w przyszłym tygodniu

![image](https://github.com/pradoslaw/coyote/assets/24964850/c1dfb28a-5b1f-4e98-a5eb-cb412619ace2)

Link do profilu https://4programmers.net/Profile/63832

**Comment by Barto-Paja** [comment]
Potwierdzam, wszystko jest w porządku.

**Comment by danon** [comment]
@Barto-Paja To super, uznajemy sprawę za zamkniętą :)

Punkty przyznane.

![image](https://github.com/pradoslaw/coyote/assets/13367735/37d20924-fd03-43b5-82d1-e1ea5a9ac895)
