### ISSUE TITLE
Czarna lista zabronionych słów

### ISSUE THREAD

**Issue by adam-boduch** [pradoslaw/coyote#76]
Czesto ludzie nie potrafia dodawac tagow, uzywajac slow takich jak pomoc, czy help. Nalezy dodac mozliwosc dodania czarnej listy slow zabronionych.

**Comment by silvuss** [comment]
Dyskusja w temacie na forum -> https://4programmers.net/Forum/Coyote/335864-zmiana_w_systemie_funkcjonowania_tagow
