### ISSUE TITLE
Kursor przy logo 4p na głównej stronie

### ISSUE THREAD

**Issue by Barto-Paja** [pradoslaw/coyote#786]
NIe jestem pewien, czy to tak powinno być, kliknąłem niechcący obok logo i pojawił mi się kursor.
![image](https://github.com/user-attachments/assets/da494d63-2a31-4612-9e06-75ef43e67cd2)

```
Brave
[Wersja 1.73.104 Chromium: 131.0.6778.204 (Oficjalna wersja) (64-bitowa)](https://brave.com/latest/)
```

**Comment by danon** [comment]
W jaki sposób można to zreprodukować?

**Comment by Barto-Paja** [comment]
1. Wejść na stronę główną
2. Kliknąć obok logo.

Przed chwilą udało mi się to zrobić w tych dwóch krokach. Chwilowo nie mam czasu na OBS, żeby to zrzucić w formie video.

**Comment by danon** [comment]
Nie mogę zreprodukować.

**Comment by Barto-Paja** [comment]
[2024-12-23 16-01-45.zip](https://github.com/user-attachments/files/18230687/2024-12-23.16-01-45.zip)
W środku film

**Comment by danon** [comment]
Nie mogę zreprodukować.

@Barto-Paja Na innych stronach też coś takiego występuje, np. w nagłówkach na githubie? Wyłącz wszystkie dodatki i spróbuj tego samego w trybie incognito.

**Comment by Barto-Paja** [comment]
Faktycznie, wyłączyłem wszystkie dodatki, tryb incognito i ten kursor dalej jest. I nie tylko na 4p ale też na githubie. No to chyba nie było tematu w takim razie. Fałszywy alarm  :)
